[theme]
base = "light"
primaryColor = "#0f766e"
backgroundColor = "#FBFBFD"
secondaryBackgroundColor = "#F1F4F8"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
